{
 "title": "HDFS – NameNode (JVM)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "NameNode JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"hdfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NameNode JVM Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"hdfs\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDFS NameNode – UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"hdfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NameNode JVM Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  jvm_memory_bytes_used{job=\"hdfs\", area=\"heap\"} /\r\n  jvm_memory_bytes_max{job=\"hdfs\", area=\"heap\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}